### ISSUE TITLE
Bagger fails to start if parent directory has spaces (Windows)

### ISSUE THREAD

**Issue by timhutch** [LibraryOfCongress/bagger#48] opened 2017-11-03 17:28 UTC
I am using Bagger 2.7.6 on Windows 7.

It appears that bagger expects the application directory to not have any spaces. I had originally extracted the application files to d:\digital preservation tools. Launching bagger triggered the error: "Could not find or load main class preservation"

Moving the bagger files to a directory with no spaces successfully works around the issue.

**Comment by timhutch** [comment] 2017-11-03 17:54
Can you point me to where the stacktrace would show up? I just got the error in the Windows command prompt window.

In any case, to reproduce: 
- install bagger on Windows in a folder like C:\Testing With Spaces
- launch bagger via bin\bagger.bat

Result:
- "Error: Could not find or load main class With"

Testing further, adding quotation marks around %APP_HOME% in the Execute bagger line of bagger.bat seems to resolve it:
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% -Dapp.home="%APP_HOME%" ...

**Comment by johnscancella** [comment] 2017-11-06 12:18
this is a duplicate of #45

**Closed by johnscancella** 2017-11-06 12:18 UTC
